# Generated by Django 5.2 on 2025-05-16 08:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_book_average_rating_book_likes_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbookrelation',
            unique_together={('user', 'book')},
        ),
    ]
